/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.3 at Sat Nov 30 13:58:16 2019. */

#include "sensor.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t Sensor_fields[4] = {
    PB_FIELD(  1, UENUM   , REQUIRED, STATIC  , FIRST, Sensor, type, type, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, Sensor, id, type, 0),
    PB_FIELD(  3, FLOAT   , REQUIRED, STATIC  , OTHER, Sensor, state, id, 0),
    PB_LAST_FIELD
};

const pb_field_t CommandMessage_fields[3] = {
    PB_FIELD(  1, UENUM   , REQUIRED, STATIC  , FIRST, CommandMessage, command, command, 0),
    PB_FIELD(  2, MESSAGE , OPTIONAL, STATIC  , OTHER, CommandMessage, parameter, command, &Sensor_fields),
    PB_LAST_FIELD
};




/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(CommandMessage, parameter) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_Sensor_CommandMessage)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(CommandMessage, parameter) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_Sensor_CommandMessage)
#endif


/* @@protoc_insertion_point(eof) */
